%% Create a study 
[STUDY ALLEEG] = std_editset( STUDY, [], 'name','IMB_main',...
        'task', 'Listening task: control vs. IB vs. PB',...
        'filename', 'IMB_main.study','filepath', './',...
        'commands', { ...
	{ 'index' 1 'load' 's01_IMB_icapMA_duple_BL_sift.set' 'subject' 's01' 'condition' 'control' }, ...
	{ 'index' 2 'load' 's02_IMB_icapMA_duple_BL_sift.set' 'subject' 's02' 'condition' 'control' }, ...
	{ 'index' 3 'load' 's04_IMB_icapMA_duple_BL_sift.set' 'subject' 's04' 'condition' 'control' }, ...
	{ 'index' 4 'load' 's05_IMB_icapMA_duple_BL_sift.set' 'subject' 's05' 'condition' 'control' }, ...
	{ 'index' 5 'load' 's06_IMB_icapMA_duple_BL_sift.set' 'subject' 's06' 'condition' 'control' }, ...
	{ 'index' 6 'load' 's07_IMB_icapMA_duple_BL_sift.set' 'subject' 's07' 'condition' 'control' }, ...
	{ 'index' 7 'load' 's09_IMB_icapMA_duple_BL_sift.set' 'subject' 's09' 'condition' 'control' }, ...
	{ 'index' 8 'load' 's01_IMB_icapMA_duple_IM_sift.set' 'subject' 's01' 'condition' 'IB' }, ...
	{ 'index' 9 'load' 's02_IMB_icapMA_duple_IM_sift.set' 'subject' 's02' 'condition' 'IB' }, ...
	{ 'index' 10 'load' 's04_IMB_icapMA_duple_IM_sift.set' 'subject' 's04' 'condition' 'IB' }, ...
	{ 'index' 11 'load' 's05_IMB_icapMA_duple_IM_sift.set' 'subject' 's05' 'condition' 'IB' }, ...
	{ 'index' 12 'load' 's06_IMB_icapMA_duple_IM_sift.set' 'subject' 's06' 'condition' 'IB' }, ...
	{ 'index' 13 'load' 's07_IMB_icapMA_duple_IM_sift.set' 'subject' 's07' 'condition' 'IB' }, ...
    { 'index' 14 'load' 's09_IMB_icapMA_duple_IM_sift.set' 'subject' 's09' 'condition' 'IB' }, ...
	{ 'index' 15 'load' 's01_IMB_icapMA_duple_SBL_sift.set' 'subject' 's01' 'condition' 'PB' }, ...
	{ 'index' 16 'load' 's02_IMB_icapMA_duple_SBL_sift.set' 'subject' 's02' 'condition' 'PB' }, ...
	{ 'index' 17 'load' 's04_IMB_icapMA_duple_SBL_sift.set' 'subject' 's04' 'condition' 'PB' }, ...
	{ 'index' 18 'load' 's05_IMB_icapMA_duple_SBL_sift.set' 'subject' 's05' 'condition' 'PB' }, ...
	{ 'index' 19 'load' 's06_IMB_icapMA_duple_SBL_sift.set' 'subject' 's06' 'condition' 'PB' }, ...
	{ 'index' 20 'load' 's07_IMB_icapMA_duple_SBL_sift.set' 'subject' 's07' 'condition' 'PB' }, ...
	{ 'index' 21 'load' 's09_IMB_icapMA_duple_SBL_sift.set' 'subject' 's09' 'condition' 'PB' }, ...
	{ 'dipselect' 0.15 } });

%% Create a study: duple_PB
eeglab
cd('/Volumes/TOSHIBA EXT/Research/Imagined_beats/real_exp/test_SSEP/PB/')
[STUDY ALLEEG] = std_editset( STUDY, [], 'name','duple_PB_WB_SB',...
        'task', 'Listening task: Compare the ERP of WB and SB in PB',...
        'filename', 'PB_WB_SB.study','filepath', './',...
        'commands', { ...
	{ 'index' 1 'load' 's01_IMB_icapMA_duple_SBL_0.set' 'subject' 's01' 'condition' 'WB' }, ...
    { 'index' 2 'load' 's01_IMB_icapMA_duple_SBL_1.set' 'subject' 's01' 'condition' 'SB' }, ...
	{ 'index' 3 'load' 's02_IMB_icapMA_duple_SBL_0.set' 'subject' 's02' 'condition' 'WB' }, ...
    { 'index' 4 'load' 's02_IMB_icapMA_duple_SBL_1.set' 'subject' 's02' 'condition' 'SB' }, ...
	{ 'index' 5 'load' 's03_IMB_icapMA_duple_SBL_0.set' 'subject' 's03' 'condition' 'WB' }, ...
    { 'index' 6 'load' 's03_IMB_icapMA_duple_SBL_1.set' 'subject' 's03' 'condition' 'SB' }, ...
	{ 'index' 7 'load' 's04_IMB_icapMA_duple_SBL_0.set' 'subject' 's04' 'condition' 'WB' }, ...
    { 'index' 8 'load' 's04_IMB_icapMA_duple_SBL_1.set' 'subject' 's04' 'condition' 'SB' }, ...
	{ 'index' 9 'load' 's05_IMB_icapMA_duple_SBL_0.set' 'subject' 's05' 'condition' 'WB' }, ...
    { 'index' 10 'load' 's05_IMB_icapMA_duple_SBL_1.set' 'subject' 's05' 'condition' 'SB' }, ...
	{ 'index' 11 'load' 's06_IMB_icapMA_duple_SBL_0.set' 'subject' 's06' 'condition' 'WB' }, ...
    { 'index' 12 'load' 's06_IMB_icapMA_duple_SBL_1.set' 'subject' 's06' 'condition' 'SB' }, ...
	{ 'index' 13 'load' 's07_IMB_icapMA_duple_SBL_0.set' 'subject' 's07' 'condition' 'WB' }, ...
    { 'index' 14 'load' 's07_IMB_icapMA_duple_SBL_1.set' 'subject' 's07' 'condition' 'SB' }, ...
	{ 'index' 15 'load' 's08_IMB_icapMA_duple_SBL_0.set' 'subject' 's08' 'condition' 'WB' }, ...
    { 'index' 16 'load' 's08_IMB_icapMA_duple_SBL_1.set' 'subject' 's08' 'condition' 'SB' }, ...
	{ 'index' 17 'load' 's09_IMB_icapMA_duple_SBL_0.set' 'subject' 's09' 'condition' 'WB' }, ...
    { 'index' 18 'load' 's09_IMB_icapMA_duple_SBL_1.set' 'subject' 's09' 'condition' 'SB' }, ...
	{ 'dipselect' 0.15 } });

%% Create a study: duple_IB
eeglab
cd('/Volumes/TOSHIBA EXT/Research/Imagined_beats/real_exp/test_SSEP/IB/')
[STUDY ALLEEG] = std_editset( STUDY, [], 'name','duple_IB_WB1_WB2',...
        'task', 'Listening task: Compare the ERP of WB1 and WB2 in IB',...
        'filename', 'IB_WB1_WB2.study','filepath', './',...
        'commands', { ...
	{ 'index' 1 'load' 's01_IMB_icapMA_duple_IM_0.set' 'subject' 's01' 'condition' 'WB2' }, ...
    { 'index' 2 'load' 's01_IMB_icapMA_duple_IM_1.set' 'subject' 's01' 'condition' 'WB1' }, ...
	{ 'index' 3 'load' 's02_IMB_icapMA_duple_IM_0.set' 'subject' 's02' 'condition' 'WB2' }, ...
    { 'index' 4 'load' 's02_IMB_icapMA_duple_IM_1.set' 'subject' 's02' 'condition' 'WB1' }, ...
	{ 'index' 5 'load' 's03_IMB_icapMA_duple_IM_0.set' 'subject' 's03' 'condition' 'WB2' }, ...
    { 'index' 6 'load' 's03_IMB_icapMA_duple_IM_1.set' 'subject' 's03' 'condition' 'WB1' }, ...
	{ 'index' 7 'load' 's04_IMB_icapMA_duple_IM_0.set' 'subject' 's04' 'condition' 'WB2' }, ...
    { 'index' 8 'load' 's04_IMB_icapMA_duple_IM_1.set' 'subject' 's04' 'condition' 'WB1' }, ...
	{ 'index' 9 'load' 's05_IMB_icapMA_duple_IM_0.set' 'subject' 's05' 'condition' 'WB2' }, ...
    { 'index' 10 'load' 's05_IMB_icapMA_duple_IM_1.set' 'subject' 's05' 'condition' 'WB1' }, ...
	{ 'index' 11 'load' 's06_IMB_icapMA_duple_IM_0.set' 'subject' 's06' 'condition' 'WB2' }, ...
    { 'index' 12 'load' 's06_IMB_icapMA_duple_IM_1.set' 'subject' 's06' 'condition' 'WB1' }, ...
	{ 'index' 13 'load' 's07_IMB_icapMA_duple_IM_0.set' 'subject' 's07' 'condition' 'WB2' }, ...
    { 'index' 14 'load' 's07_IMB_icapMA_duple_IM_1.set' 'subject' 's07' 'condition' 'WB1' }, ...
	{ 'index' 15 'load' 's08_IMB_icapMA_duple_IM_0.set' 'subject' 's08' 'condition' 'WB2' }, ...
    { 'index' 16 'load' 's08_IMB_icapMA_duple_IM_1.set' 'subject' 's08' 'condition' 'WB1' }, ...
	{ 'index' 17 'load' 's09_IMB_icapMA_duple_IM_0.set' 'subject' 's09' 'condition' 'WB2' }, ...
    { 'index' 18 'load' 's09_IMB_icapMA_duple_IM_1.set' 'subject' 's09' 'condition' 'WB1' }, ...
	{ 'dipselect' 0.15 } });