%% Save the average data to an EEG .set file 
cfg_path = '/Volumes/TOSHIBA/Research/Imagined_beats/real_exp/sifts/SIFT_input/cfg';
cd(cfg_path)
load('newpre_prepData_cfg.mat'); 
load('newest_fitMVAR_cfg.mat');
load('newest_mvarConnectivity_cfg.mat');

cd('/Volumes/TOSHIBA/Research/Imagined_beats/real_exp/results/Main_task/sift/AM4b')
load('SIFTout_AM4b_M30_N20_no_bc.mat')
EEG = pop_loadset('SIFTout_AM4b_M30_N20_no_bc.set');

nsub = size(SIFTout,1);
nmeter = size(SIFTout,2);
ncond = size(SIFTout,3);

for sub = 1:nsub
    for meter = 1:nmeter
        for cond = 1:ncond
            dDTF08(sub,meter,cond,:,:,:,:) = squeeze(SIFTout{sub,meter,cond}.dDTF08);
        end
    end
end
duple = 1;
triple = 2;
BL = 1;
PM = 2;
IM = 3;
TAP = 4;

mean_dDTF08 = squeeze(mean(dDTF08(:,duple,IM,:,:,:,:),1));
EEG.CAT.Conn.dDTF08 = mean_dDTF08;
EEG.CAT.configs0 = EEG.CAT.configs;
EEG.CAT.configs = struct('pre_prepData',EEG.CAT.configs0.pre_prepData,'est_fitMVAR',EEG.CAT.configs0.est_fitMVAR,'est_mvarConnectivity',EEG.CAT.configs0.est_mvarConnectivity);

%% IMB
% rmpath('/data/common/matlab/eeglab/') % Use the saved eeglab so that the
% eeglab
clear
close all
clc

Averagetime = true;

cfg_path = '/data/projects/zoe/ImaginedBeats/script/analysis/cfg';
cd(cfg_path)

% Load the dataset that has an EEG structure averaged across subjects
meter = {'duple'};
cond = {'BL','PM','IM','TAP'};

NumPermutations = 200;

for nmeter = 1:length(meter)
    for ncond = 1:length(cond)
        filename = strcat('all_SIFTout_AM4b_M30_N20_no_bc_',meter(nmeter),'_',cond(ncond),'.set');
        EEG = pop_loadset(filename{1});
        EEG.CAT.configs.est_mvarConnectivity = rmfield(EEG.CAT.configs.est_mvarConnectivity,'winlen'); % extra field to cause error otherwise 
        EEG.CAT.configs.est_mvarConnectivity = rmfield(EEG.CAT.configs.est_mvarConnectivity,'winstep'); % extra field to cause error otherwise 
        
        if Averagetime
        EEG.CAT.Conn.dDTF08(:,:,:,1) = squeeze(mean(EEG.CAT.Conn.dDTF08,4)); % the first colume of the last dim is the averaged time matrix for each direction, frequency
        end
        
        [EEG.CAT.PConn,g] = stat_surrogateGen('ALLEEG',EEG,'Mode',{'PhaseRand','NumPermutations',NumPermutations});
        [EEG.CAT.stats, ~,cfg] = stat_surrogateStats(EEG);
        pop_saveset(EEG,'filename',strcat('avetime_sstat_',filename{1}));
    end
end

%% Localizer
% rmpath('/data/common/matlab/eeglab/') % Use the saved eeglab so that the
% eeglab
clear
close all
clc

Averagetime = true;

cfg_path = '/data/projects/zoe/ImaginedBeats/script/analysis/cfg';
cd(cfg_path)

% Load the dataset that has an EEG structure averaged across subjects
% files are generated by averaging SIFTout_M30_xxx to put in 
% the "shell" structure s02_evtag_512_clean_binica_dipfit_tap1_e.set
% see sift_fast.m
trials = {'all_SIFTout_M30_rdlisten2.set','all_SIFTout_M30_tap1.set','all_SIFTout_M30_sync3s.set','all_SIFTout_M30_sync3t.set'};

NumPermutations = 500;

for ntrials = 1:length(trials)
        filename = trials(ntrials);
        EEG = pop_loadset(filename{1});
        EEG.CAT.configs.est_mvarConnectivity = rmfield(EEG.CAT.configs.est_mvarConnectivity,'winlen'); % extra field to cause error otherwise 
        EEG.CAT.configs.est_mvarConnectivity = rmfield(EEG.CAT.configs.est_mvarConnectivity,'winstep'); % extra field to cause error otherwise 

        if Averagetime
        EEG.CAT.Conn.dDTF08(:,:,:,1) = squeeze(mean(EEG.CAT.Conn.dDTF08,4)); % the first colume of the last dim is the averaged time matrix for each direction, frequency
        end
        
        [EEG.CAT.PConn,g] = stat_surrogateGen('ALLEEG',EEG,'Mode',{'PhaseRand','NumPermutations',NumPermutations});
        [EEG.CAT.stats, ~,cfg] = stat_surrogateStats(EEG);
        pop_saveset(EEG,'filename',strcat('avetime_sstat_',filename{1}));
end

%% Visualization
% t-f
clear 
clc

EEG = pop_loadset('sstat_all_SIFTout_M30_sync3t.set');

figure;imagesc(EEG.CAT.Conn.erWinCenterTimes,EEG.CAT.Conn.freqs,squeeze(EEG.CAT.Conn.dDTF08(1,2,:,:)));axis xy;colormap(jet)
ylim([11 40])
xlabel('Time (s)')
ylabel('Frequency (Hz)')

figure;imagesc(EEG.CAT.Conn.erWinCenterTimes,EEG.CAT.Conn.freqs,squeeze(EEG.CAT.stats.dDTF08.pval(1,2,:,:))<0.05);axis xy;colormap(jet)
ylim([11 40])
xlabel('Time (s)')
ylabel('Frequency (Hz)')

%%
% average across time and store in the first colume 
clear 
close all
clc

files = dir('avetime*.set');
names = {files.name};

figure;
for i = 1:length(files)
    EEG = pop_loadset(names(i));
    parts_name = cellstr(split(names(i) ,{'_','.'}));
    subplot(4,1,i);plot(EEG.CAT.Conn.freqs,squeeze(EEG.CAT.Conn.dDTF08(1,2,:,1)));
    xlabel('Frequency (Hz)');title(parts_name{end-1})
end

figure;
for i = 1:length(files)
    EEG = pop_loadset(names(i));
    parts_name = cellstr(split(names(i) ,{'_','.'}));
    subplot(4,1,i);plot(EEG.CAT.Conn.freqs,squeeze(EEG.CAT.stats.dDTF08.pval(1,2,:,1)));
    xlabel('Frequency (Hz)');title(parts_name{end-1});ylim([0 0.1])
end

figure;

for i = 1:length(files)
    EEG = pop_loadset(names(i));
    parts_name = cellstr(split(names(i) ,{'_','.'}));
    subplot(4,1,i);plot(EEG.CAT.Conn.freqs,squeeze(EEG.CAT.Conn.dDTF08(2,1,:,1)));
    xlabel('Frequency (Hz)');title(parts_name{end-1})
end

figure;
for i = 1:length(files)
    EEG = pop_loadset(names(i));
    parts_name = cellstr(split(names(i) ,{'_','.'}));
    subplot(4,1,i);plot(EEG.CAT.Conn.freqs,squeeze(EEG.CAT.stats.dDTF08.pval(2,1,:,1)));
    xlabel('Frequency (Hz)');title(parts_name{end-1});ylim([0 0.1])
end

%%
figure;imagesc(EEG.CAT.Conn.erWinCenterTimes,EEG.CAT.Conn.freqs,-log(squeeze(EEG.CAT.stats.dDTF08.pval(2,1,:,:)))>-log(0.05));axis xy;colormap(jet)
ylim([0 40])
xlabel('Time (s)')
ylabel('Frequency (Hz)')